Update build_deploy.yml

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -8,7 +8,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
@@ -36,21 +36,19 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-1
-        
-    - name: Clean up kubectl
+
+    - name: Clean up existing kubectl
       run: |
         sudo rm -f /usr/local/bin/kubectl || true
-        
+
     - name: Install kubectl
       run: |
-        curl -LO "https://amazon-eks.s3.us-west-2.amazonaws.com/$(aws eks describe-cluster --name HTXAssignment --query "cluster.version" --output text)/bin/linux/amd64/kubectl"
+        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         chmod +x ./kubectl
         sudo mv ./kubectl /usr/local/bin
-        
-    - name: Verify kubectl installation
-      run: |
-        kubectl version --client
-        
+        echo "kubectl version:"
+        /usr/local/bin/kubectl version --client
+
     - name: Update kubeconfig
       run: |
         aws eks --region ap-southeast-1 update-kubeconfig --name HTXAssignment
@@ -60,3 +58,7 @@ jobs:
         kubectl apply -f k8s/configmap.yaml || { echo "Failed to apply configmap"; exit 1; }
         kubectl apply -f k8s/secrets.yaml || { echo "Failed to apply secrets"; exit 1; }
         kubectl apply -f k8s/deployment.yaml || { echo "Failed to apply deployment"; exit 1; }
+
+    - name: Check Pod Status
+      run: |
+        kubectl get pods || { echo "Failed to get pods"; exit 1; }
