Update build_deploy.yml

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -55,9 +55,9 @@ jobs:
 
     - name: Deploy to Kubernetes
       run: |
-        kubectl apply -f k8s/configmap.yaml || { echo "Failed to apply configmap"; exit 1; }
-        kubectl apply -f k8s/secrets.yaml || { echo "Failed to apply secrets"; exit 1; }
-        kubectl apply -f k8s/deployment.yaml || { echo "Failed to apply deployment"; exit 1; }
+        kubectl apply -f HTXApp/k8s/configmap.yaml || { echo "Failed to apply configmap"; exit 1; }
+        kubectl apply -f HTXApp/k8s/secrets.yaml || { echo "Failed to apply secrets"; exit 1; }
+        kubectl apply -f HTXApp/k8s/deployment.yaml || { echo "Failed to apply deployment"; exit 1; }
 
     - name: Check Pod Status
       run: |
